train_configs:
  # Device
  device: "cpu"
  # Logging and outputs
  logging_id: "Client1"
  logging_output_dirname: "./output"
  logging_output_filename: "result"

# Local dataset
data_configs:
  dataset_path: "./dataset/GW_dataset.py"
  dataset_name: "get_wavedata"
  dataset_kwargs:
    num_clients: 2
    client_id: 0
    dataset_dir: "/scratch/bbke/parthpatel7173/WaveNet_Data/combined_spin/"
    partition_strategy: "class_noniid"
    visualization: True
    output_dirname: "./output"
    output_filename: "visualization.pdf"

comm_configs:
  grpc_configs:
    server_uri: localhost:50051
    max_message_size: 1048576
    use_ssl: False