client_configs:
  train_configs:
    # Local trainer
    trainer: "GWTrainer"
    mode: "epoch"
    num_local_epochs: 2
    optim: "Adam"
    optim_args:
      lr: 0.001
    # Loss function
    loss_fn_path: "./loss/bceloss.py"
    loss_fn_name: "BCELoss"
    # Client validation
    do_validation: True
    do_pre_validation: True
    metric_path: "./metric/acc.py"
    metric_name: "accuracy"
    # Differential privacy
    use_dp: False
    epsilon: 1
    clip_grad: False
    clip_value: 1
    clip_norm: 1
    # Data loader
    train_batch_size: 32
    val_batch_size: 32
    train_data_shuffle: True
    val_data_shuffle: False
    n_channels: 3
    num_workers: 8
    num_nodes: 1
    noise_dir: "/scratch/bbke/parthpatel7173/WaveNet_data/Gaussian_Noise/"
    dataset_dir: "/scratch/bbke/parthpatel7173/WaveNet_data/combined_spin/"
    checkpoint_dir: "/scratch/bbke/parthpatel7173/WaveNet_training/checkpoints/"
    # data_dir: "ssfds"
    
  model_configs:
    model_path: "./model/GWnet.py"
    model_name: "full_module"
  
  comm_configs:
    compressor_configs:
      enable_compression: False
      # Used if enable_compression is True
      lossy_compressor:  "SZ2"
      lossless_compressor: "blosc"
      error_bounding_mode: "REL"
      error_bound: 1e-3
      flat_model_dtype: "np.float32"
      param_cutoff: 1024

server_configs:
  scheduler: "SyncScheduler"
  scheduler_kwargs:
    num_clients: 2
    same_init_model: True
  aggregator: "FedAvgAggregator"
  aggregator_kwargs:
    client_weights_mode: "equal"
  device: "cpu"
  num_global_epochs: 3
  server_validation: False
  logging_output_dirname: "./output"
  logging_output_filename: "result"
  comm_configs:
    grpc_configs:
      server_uri: localhost:50051
      max_message_size: 1048576
      use_ssl: False